version: '3.1'
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - products:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=products
volumes:
  products:
