### LISTAR UM PRODUTO ESPECÍFICO
GET http://127.0.0.1:5000/products/fcf4728c-8aab-45bf-8924-4d761f2836ed
Content-Type: application/json

### CADASTRAR UM PRODUTO
POST http://127.0.0.1:5000/products
content-type: application/json

{
    "name": "Camisa Preta",
    "description": "Camisa de algodão, com gola V",
    "price": 70
}

### ATUALIZAR UM PRODUTO
PUT http://127.0.0.1:5000/products/fcf4728c-8aab-45bf-8924-4d761f2836ed
content-type: application/json

{
    "name": "ATUALIZADO RECENTEMENTE",
    "description": "atualizando produto",
    "price": 202
}

### REMOVER UM PRODUTO ESPECÍFICO
DELETE http://127.0.0.1:5000/products/c2961fbf-0f45-4fab-a47f-9afce0dacf2d
Content-Type: application/json

### LISTAR TODOS OS PRODUTOS
GET http://127.0.0.1:5000/products
content-type: application/json