### LISTAR UM PRODUTO ESPECÍFICO
GET http://127.0.0.1:5000/products/7f8b030c-e1b9-447c-a502-3bdebd825618
Content-Type: application/json

### CADASTRAR UM PRODUTO
POST http://127.0.0.1:5000/products
content-type: application/json

{
    "name": "Camisa Preta",
    "description": "Camisa de algodão, com gola V",
    "price": 70
}

### ATUALIZAR UM PRODUTO
PUT http://127.0.0.1:5000/products/7f8b030c-e1b9-447c-a502-3bdebd825618
content-type: application/json

{
    "name": "ATUALIZADO RECENTEMENTE",
    "description": "atualizando produto",
    "price": 202
}

### REMOVER UM PRODUTO ESPECÍFICO
DELETE http://127.0.0.1:5000/products/faksdfasdfasdf
Content-Type: application/json

### LISTAR TODOS OS PRODUTOS
GET http://127.0.0.1:5000/products
content-type: application/json